# Generated by Django 2.2.5 on 2019-09-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubbing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='name',
            field=models.CharField(default='', max_length=300),
        ),
    ]
