# Generated by Django 2.2.5 on 2019-09-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubbing', '0002_purchase_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='max_cost',
            field=models.BigIntegerField(),
        ),
    ]
