# Generated by Django 2.2.5 on 2019-09-17 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubbing', '0003_auto_20190918_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='name',
        ),
    ]
