# Generated by Django 2.2.5 on 2019-09-18 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubbing', '0004_remove_purchase_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='item',
        ),
        migrations.AddField(
            model_name='order',
            name='purchase',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='clubbing.Purchase'),
            preserve_default=False,
        ),
    ]
