# Generated by Django 2.2.5 on 2019-09-18 20:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubbing', '0005_auto_20190918_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='members',
            field=models.ManyToManyField(related_name='members', through='clubbing.Order', to=settings.AUTH_USER_MODEL),
        ),
    ]
