# Generated by Django 2.2.5 on 2019-09-20 21:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubbing', '0006_purchase_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='members',
            field=models.ManyToManyField(related_name='members_purchase', through='clubbing.Order', to=settings.AUTH_USER_MODEL),
        ),
    ]
