# Generated by Django 2.2.5 on 2019-09-20 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubbing', '0008_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatars/none.png', unique=True, upload_to='avatars'),
        ),
    ]
